### ISSUE TITLE
[Insight] Text files should end with a newline character - in src/phpspec.yml, line 5

### ISSUE THREAD

**Issue by tmknom** [tmknom/tech-study#17]
**[in src/phpspec.yml, line 5](https://github.com/tmknom/tech-study/blob/8ca546a07e7454b5f1310571c9a2ad5787c2f0af/src/phpspec.yml#L5)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
suites:
    main:
        namespace: App
        psr4_prefix: App
        src_path: app
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/a157cee3-2b5b-4d0a-bab4-376d7903871c/analyses/173)_
